#  _____     _ _ _ _
# |_   _| __(_) | (_)_   _ _ __ ___
#   | || '__| | | | | | | | '_ ` _ \
#   | || |  | | | | | |_| | | | | | |
#   |_||_|  |_|_|_|_|\__,_|_| |_| |_|

#---------------[ Server ]---------------#
server:
  server-list-motd: "&cPlease define a motd in the config.yml"
  motd:
    - "&8<<<--->>> &aServer &8<<<--->>>"
    - "&7Welcome &6[USERNAME]&7!"
    - "&7There are currently &6[ONLINE]&7/&6[SLOTS] players."
    - "&7Have fun! ^_^/"

#---------------[ Player Join ]---------------#
join:
  message: "&b[USERNAME] &9has joined the game!"

#---------------[ Player Leave ]---------------#
leave:
  message: "&b[USERNAME] &9has left the game!"

#---------------[ Broadcast ]---------------#
Broadcast:
  - " "
  - "&8[&a*&8]&b&m------------------&8[ &a&lBroadcast &8]&b&m------------------&8[&a*&8]"
  - " "
  - "[msg]"
  - " "
  - "&8[&a*&8]&b&m-------------------------------------------------&8[&a*&8]"

#---------------[ Ability ]---------------#
ability:
  auto-respawn: false
  vanish:
    prevent-item-pickup/drop: true
    spectator-mode: true
    god-mode: true
  afk:
    auto-afk:
      enabled: true
      time-until-idle: 60
      #seconds
      kick-on-afk: false
    auto-unafk: true