#  _____     _ _ _ _
# |_   _| __(_) | (_)_   _ _ __ ___
#   | || '__| | | | | | | | '_ ` _ \
#   | || |  | | | | | |_| | | | | | |
#   |_||_|  |_|_|_|_|\__,_|_| |_| |_|

#---------------[ Motd ]---------------#
Server List Motd: "&4Please define a motd in the conig.yml"
Motd:
  - "&8<<<--->>> &aServer &8<<<--->>>"
  - "&7Welcome &6[USERNAME]&7!"
  - "&7There are currently &6[ONLINE]&7/&6[SLOTS] players."
  - "&7Have fun! ^_^/"

#---------------[ Player Join ]---------------#
Join Message: "&b[USERNAME] &9has joined the game!"
Temporary God Mode: 10
#Temporary god mdoe in seconds.

#---------------[ Player Leave ]---------------#
Leave Message: "&b[USERNAME] &9has left the game!"



