#  _____     _ _ _ _
# |_   _| __(_) | (_)_   _ _ __ ___
#   | || '__| | | | | | | | '_ ` _ \
#   | || |  | | | | | |_| | | | | | |
#   |_||_|  |_|_|_|_|\__,_|_| |_| |_|

#---------------[ Motd ]---------------#
Server List Motd: "&cPlease define a motd in the config.yml"
Motd:
  - "&8<<<--->>> &aServer &8<<<--->>>"
  - "&7Welcome &6[USERNAME]&7!"
  - "&7There are currently &6[ONLINE]&7/&6[SLOTS] players."
  - "&7Have fun! ^_^/"

#---------------[ Player Join ]---------------#
Join:
  message: "&b[USERNAME] &9has joined the game!"
  temporary god mode: 10
#Temporary god mode in seconds.

#---------------[ Player Leave ]---------------#
Leave:
  message: "&b[USERNAME] &9has left the game!"

#---------------[ Broadcast ]---------------#
Broadcast:
  line clear: true
  line clearing between header and footer: true
  prefix:
   enabled: false
   set: "&8[&a&lBroadcast&8]"
  header:
    enabled: true
    set: "&8[&a*&8]&b&m------------------&8[ &a&lBroadcast &8]&b&m------------------&8[&a*&8]"
  footer:
    enabled: true
    set: "&8[&a*&8]&b&m-------------------------------------------------&8[&a*&8]"

#---------------[ Vanish ]---------------#
Vanish:
  prevent item pickup/drop: true
  god mode: true

#---------------[ AFK ]---------------#
AFK:
  auto afk:
    enabled: true
    time until idle: 60
    #Time until idle in seconds.
    kick on afk: false
  god mode: true
  auto unafk: true
  #When the player makes any action, it takes them out of afk mode.
