#  _____     _ _ _ _
# |_   _| __(_) | (_)_   _ _ __ ___
#   | || '__| | | | | | | | '_ ` _ \
#   | || |  | | | | | |_| | | | | | |
#   |_||_|  |_|_|_|_|\__,_|_| |_| |_|

#---------------[ Motd ]---------------#
Server List Motd: "&cPlease define a motd in the config.yml"
Motd:
  - "&8<<<--->>> &aServer &8<<<--->>>"
  - "&7Welcome &6[USERNAME]&7!"
  - "&7There are currently &6[ONLINE]&7/&6[SLOTS] players."
  - "&7Have fun! ^_^/"

#---------------[ Player Join ]---------------#
Join:
  message: "&b[USERNAME] &9has joined the game!"

#---------------[ Player Leave ]---------------#
Leave:
  message: "&b[USERNAME] &9has left the game!"

#---------------[ Broadcast ]---------------#
Broadcast:
  - " "
  - "&8[&a*&8]&b&m------------------&8[ &a&lBroadcast &8]&b&m------------------&8[&a*&8]"
  - " "
  - "[msg]"
  - " "
  - "&8[&a*&8]&b&m-------------------------------------------------&8[&a*&8]"

#---------------[ Vanish ]---------------#
Vanish:
  prevent item pickup/drop: true
  spectator mode: true
  god mode: true

#---------------[ AFK ]---------------#
AFK:
  auto afk:
    enabled: true
    time until idle: 60
    #Time until idle in seconds.
    kick on afk: false
  god mode: true
  auto unafk: true
  #When the player makes any action, it takes them out of afk mode.
