author: LordSaad44
description: The Premium Essentials.
main: me.lordsaad.trillium.Trillium
name: Trillium
version: 0.3
commands:
  trillium:
    description: The main command of the plugin.
    usage: /trillium
    aliases: [tr]
  back:
    description: Teleport to the last place you teleported from.
    usage: /back
  inventory:
    description: Open a crafting table or view someone's inventory or enderchest.
    usage: /inv <player [enderchest]/crafting>
    aliases: [inv]
  message:
    description: Send a message to a player.
    usage: /message <sender> <message>
    aliases: [msg, m]
  commandbinder:
    description: Bind a command to a block to activate that command when it's either touched or walked through.
    usage: /cb <touch/walk> <console/player> <command>
    aliases: [cmdbinder, cmdb, cb, cbinder, cbind]
  kittybomb:
    description: KITTEH BAMB!!
    usage: /kittybomb
    aliases: [kittehbamb, kittehbomb, kittybamb, kittyb, kbomb, kb]
  me:
    description: Share your feelings/thoughts to everyone.
    usage: /me <message>
  killall:
    description: Kill anything in a radius.
    usage: /killall <radius> <mobs/players/animals/monsters/items/everything>
  smite:
    description: Strike lightning upon someone .
    usage: /smite [player]
    aliases: [thor, lightning, thunder]
  report:
    description: Send a report to the admins/mods
    usage: /report <msg>
  reports:
    description: View the reports, remove a report, or clear the report list.
    usage: /reports [remove <index number>/clear]
  nickname:
    description: Set a nickname for yourself
    usage: /nick [player]
    aliases: [nick]