author: LordSaad44
description: The Premium Essentials.
main: me.lordsaad.trillium.Main
name: Trillium
version: 1.0
commands:
  trillium:
    description: The main command of the plugin.
    usage: /trillium
    aliases: [tr]
  motd:
    description: View/Edit the motd.
    usage: /motd
  teleport:
    description: Teleport to any player.
    usage: /teleport <player> [player]
    aliases: [tp]
  teleportrequest:
    description: Request permission to teleport to any player.
    usage: /tpr <player>
    aliases: [tpr]
  teleportrequestaccept:
    description: Accept to have a player teleport to you.
    usage: /tpra
    aliases: [tpra]
  teleportrequestdeny:
    description: Deny a player teleport request.
    usage: /tprd
    aliases: [tprd]
  teleportrequesthere:
    description: Request permission to have a player teleport to you.
    usage: /tprh <player>
    aliases: [tprh]
  teleporthere:
    description: Teleport a player to you.
    usage: /tph <player>
    aliases: [tph]